describe('Split', function() {
	beforeEach(function() {
		cy.fixture("blueprints.json").as("blueprints")
		cy.fixture("split_results.json").as("results")
		cy.goto(".menu-split", "Split")
	})
	it('Split a huge blueprint into 2x2', function() {
		cy.pasteBlueprint(this.blueprints.huge)
		// XXX: the clear here deadlocks chromium
		// cy.get(".input-split-tile-size input").clear().type("68")
		let ts = cy.get(".input-split-tile-size input")
		ts.should("have.value", "64")
		ts.type("{end}{backspace}8")
		cy.assertResultBlueprint(this.results.huge2x2)
	})
	it('Blueprints are aligned to prevent problems with the traingrid (odd)', function() {
		cy.pasteBlueprint(this.blueprints.traingridOffset)
		cy.get(".input-split-tile-size input").should("have.value", "64")
		cy.assertResultBlueprint(this.results.traingridOffset64)
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").should("have.value", "65")
		cy.assertResultBlueprint(this.results.traingridOffset64)
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").should("have.value", "66")
		cy.assertResultBlueprint(this.results.traingridOffset66)
	})
	it('Blueprints are aligned to prevent problems with the traingrid (even)', function() {
		cy.pasteBlueprint(this.blueprints.traingridNoOffset)
		cy.get(".input-split-tile-size input").should("have.value", "64")
		cy.assertResultBlueprint(this.results.traingridNoOffset64)
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").should("have.value", "67")
		cy.assertResultBlueprint(this.results.traingridNoOffset64)
		cy.get(".input-split-tile-size input").type("{uparrow}")
		cy.get(".input-split-tile-size input").should("have.value", "68")
		cy.assertResultBlueprint(this.results.traingridNoOffset68)
	})
	it('One line blueprints work', function() {
		cy.pasteBlueprint(this.blueprints.beltline64)
		cy.get(".input-split-tile-size input").should("have.value", "64")
		cy.assertResultBlueprint(this.results.beltline64)
	 	cy.get(".input-split-tile-size input").type("{selectall}32")
		cy.assertResultBlueprint(this.results.beltline32)
	})
})
